### ISSUE TITLE
path fix for email

### ISSUE THREAD

**Issue by Zombienomicon** [extend-a-story/extend-a-story#1]
Hi,

I noticed that in the email sent to tell you a new episode has been made, it had only put read.php<episode info> and no the full path.

Not sure if that's due to my site being a https and not a http but I couldn't see anything in the code that indicated that.

My fix is below:

ORIGINAL CODE: line 697
$readEpisodeURL . "?episode=" . $episode . "\n" .

CHANGED CODE:
"<full directory path to where read.php is>" . $readEpisodeURL . "?episode=" . $episode . "\n" .

so for example for mine the changed code reads

"https://thezombienomicon.com/eas/" . $readEpisodeURL . "?episode=" . $episode . "\n" .

That results in a functional link within the email to the specific new episode.

**Comment by jjweston** [comment]
In your story settings, what have you set "Read Episode URL" to? This should be the full URL with the protocol, host, domain, and path to your read.php script for your story. In your example, "Read Episode URL" should be "https://thezombienomicon.com/eas/read.php".

Let me know if that helps.

**Comment by jjweston** [comment]
Over two years have passed with no comment on this issue. I'm not aware of any problems with the code for sending emails. I'm closing this issue.
